---
title: "Transform dataset"
date: "`r Sys.Date()`"
bibliography: references.bib
biblio-style: apalike
---

## About

### Description

<!-- The aim of this script -->

### Usage

<!-- How to run this script: what input it requires and output produced -->

## Setup

```{r setup}
# Script-specific options or packages

```

## Run

### Second Person Plurals

```{r}
updated_plurals <- left_join(join_tweets_to_states(plurals),census_regions)
left_join(join_tweets_to_states(plurals),census_regions)
```

```{r}
updated_plurals %>% 
  select(search_term, census_region) %>% # select key variables
  skim() %>% # get custom data summary
  yank("factor") # only show factor-oriented information
```

### Outdoor Sales

```{r}
updated_sales <- left_join(join_tweets_to_states(sale),census_regions)
left_join(join_tweets_to_states(sale),census_regions)
```

```{r}
updated_sales %>% 
  select(search_term, census_region) %>% # select key variables
  skim() %>% # get custom data summary
  yank("factor") # only show factor-oriented information
```

### Gym Shoes

```{r}
updated_shoes <- left_join(join_tweets_to_states(shoes),census_regions)
left_join(join_tweets_to_states(shoes),census_regions)
```

```{r}
updated_shoes %>% 
  select(search_term, census_region) %>% # select key variables
  skim() %>% # get custom data summary
  yank("factor") # only show factor-oriented information
```

### Soft Drinks

```{r}
updated_tonix <- left_join(join_tweets_to_states(tonix),census_regions)
left_join(join_tweets_to_states(tonix),census_regions)
```

```{r}
updated_tonix %>% 
  select(search_term, census_region) %>% # select key variables
  skim() %>% # get custom data summary
  yank("factor") # only show factor-oriented information
```

### Major Roads

```{r}
updated_roads <- left_join(join_tweets_to_states(roads),census_regions)
left_join(join_tweets_to_states(roads),census_regions)
```

```{r}
updated_roads %>% 
  select(search_term, census_region) %>% # select key variables
  skim() %>% # get custom data summary
  yank("factor") # only show factor-oriented information
```
<!-- Steps involved in transforming the data for analysis -->

## Finalize

### Log

<!-- Any description that will be helpful to understand the results of this script and how it contributes to the aims of the project -->

### Session

<details><summary>View session information</summary>

```{r, child="_session-info.Rmd"}
```

</details>

```{r cleanup, echo=FALSE}
rm(list = ls()) # clean working environment
```

## References
